# Generated by Django 3.2 on 2022-11-27 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_filmwork_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmwork',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='filmwork',
            name='persons',
        ),
    ]
